### ISSUE TITLE
having a search domain set (through dhcp) stops k3s from starting.

### ISSUE THREAD

**Issue by cnf** [rancher/k3os#106]
When a search domain is set through DHCP, k3os/k3s? tries to resolve localhost.<search_domain> through dns. If that doesn't respond with 127.0.0.1 for whatever reason, k3s won't come up.

My dns server responds to *.<searchdomain> that isn't specifically set with a set IP.

This is k3os 0.2.0

**Comment by Himura2la** [comment]
We have exactly the same problem. Our organization has a large domain network with very different devices, and somewhere in this network there are Samsung TV-sets (with SmartViewSDK) which send `localhost` hostname to a DHCP server. This makes `localhost.<our_domain>` resolve to a TV-set IP address instead of `127.0.0.1` in k3os. This causes random errors everywhere, please pay attention to this issue, we can't use k3s in our team because of this.

**Comment by dweomer** [comment]
@cnf @Himura2la:
I think this should be solved by #170 which is included in [v0.3.0-rc1](https://github.com/rancher/k3os/releases/tag/v0.3.0-rc1). Please re-open if this remains unfixed for you.
