### ISSUE TITLE
Changing Hostname creates orphaned node

### ISSUE THREAD

**Issue by joharper54SEG** [rancher/k3os#159]
I am setting the hostname via /var/lib/rancher/k3os/config.yaml.  After a reboot the hostname does change but if you run kubectl get node you see 2 entries, 1 being the old hostname in a NotReady Status.

s10618svr [~]$ kubectl get node
NAME        STATUS     ROLES    AGE   VERSION
k3os-3098   NotReady   <none>   16h   v1.14.1-k3s.4
s10618svr   Ready      <none>   16h   v1.14.1-k3s.4

**Comment by dweomer** [comment]
@ibuildthecloud @erikwilson this is the expected behavior, no?

**Comment by dweomer** [comment]
@joharper54SEG I believe that this is the expected behavior when changing the hostname out from underneath k3s. You may be better served by supplying something like the below in your k3OS config (either at provisioning time or boot time via user-data):
```yaml
k3os:
  ks3_args:
  - "--node-name=s10618svr"
```

Be warned though that using duplicate names for agents will incur dysfunction in your cluster.
See https://github.com/rancher/k3s/issues/857.
