### ISSUE TITLE
Cannot boot offbrand NUC with UEFI

### ISSUE THREAD

**Issue by zlogic** [rancher/k3os#215]
I have an [HKC MPAYF-3350](https://www.amazon.co.uk/HKC-MPAYF-3350-Desktop-Celeron-Graphics/dp/B07C8G4GX3) NUC. (Intel Celeron N3350, 4GB RAM, 32GB internal storage)

When trying to boot from a USB flash drive with the k3os ISO image, I just get a blank screen with an `_` underscore character - it's not even blinking. It happens before the grub menu appears.

I've tried using dd and rufus to create the bootable flash drive, with the same results.

Booting from an Ubuntu 19.04 flash drive works fine on that system.
I can also use https://github.com/rancher/k3os/blob/master/install.sh from an Ubuntu flash drive to install k3os; this way, `grub-install` and the EFI files are used from Ubuntu. With this approach, the k3os system is able to boot.

However if I run `grub-install` from a booted k3os system and switch to the `alpine` UEFI OS in the BIOS (one which is created by the k3os' `grub-install`), I get the same issue when booting from a k3os iso: black screen with a non-flashing underscore `_` cursor.

The system has an eMMC internal system drive (`/dev/mmcblk1`). It seems to me that something is missing from `bootx64.efi` from the k3os iso, and also from `grub-install` in a k3os system. Possibly, something related to mmc or sd drivers.

It's possible this is related to https://github.com/rancher/k3os/issues/111 (but on an amd64 system).

**Comment by dweomer** [comment]
@zlogic all of our EFI bits come from Alpine Linux (3.9 currently) so it might be useful to flash the Alpine installation media and try booting from that. Alpine is currently at 3.10.x so if booting that media **does** work please also download the latest 3.9.x media and attempt to boot/install from that. My hunch is that there is something missing/outdated with 3.9.x and that it has been resolved with 3.10.x.

**Comment by zlogic** [comment]
@dweomer I've tried to reproduce the problem - both Alpine 3.9 and Alpine 3.10 are showing the exact same problem.

**Comment by djmrr** [comment]
@zlogic 

I was having a heck of a time trying to get going with the live install via USB on an Intel Atom little board.

But!
My brain is very dumb.  Like ridiculously so.  

I think I was formatting the USB stick I had all the wrong ways.
I ended up following the Alpine Linux Guide to creating a bootable usb stick, mainly the format section:

https://wiki.alpinelinux.org/wiki/Create_a_Bootable_USB#Creating_a_bootable_Alpine_Linux_USB_Stick_from_the_command_line#Format_USB_stick

^doing all those things making it like a mkfs.vfat and what not. 

Then ended up running:
```
sudo dd if=k3os-amd64.iso of=/dev/sda status="progress"
```

Once that finished, shoved it in the little thing and it booted right up.
I think the thing is that in the guide, that Alpine Linux has, it PURPOSEFULLY notes, in order to make the device bootable with fdisk, you gotta set the boot flag with "a", before writing the changes...
I'm thinking that when you set the boot flag it tosses GNU Grub on there, me thinks... but...I could totally be wrong haha!

I'm just a hack at life, waste 3hrs trying to get running with k3os because I'm dumb, and there's not a ton of gratification because now I need to learn all things kubernetes, I'm a washed up wanna be software engineer (but really I just like to tinker) that will probably burn out and steal bread from pigeons as I live on a park bench ahaha #tmi

**Comment by erkki** [comment]
Running into the same issue with a NUC10i7FN

**Comment by erkki** [comment]
Followup, bumping k3os base image to alpine 3.12 fixed this for me.

**Comment by zlogic** [comment]
I can confirm that using Alpine 3.12 fixed the issue for me as well.

**Comment by Confusingboat** [comment]
Alpine 3.12 also fixed this issue for the ODroid H2+

ISO available here: https://www.mediafire.com/file/88jqv91ddgmf5lb/k3os-amd64-v0.11.0-alpine312.iso/file

**Comment by cdeadspine** [comment]
I think certain hardware manufacturers can screw this whole thing up too:
```
On an Acer : Veriton L4610G (apparently this model is for windows only somehow? they have one that ends in L for "linux" whatever that means)
```
I can boot into live mode, and installation indicates no problems, but a reboot will never detect whatever boot system is being installed. I also tried Alpine linux installation 3.12.1, same thing.
```
Troubleshooting included:
sudo fdisk /dev/sda
- none of the partitions have a "boot flag" that will survive a restart, tried manually setting boot flag for the first "GPT" that contains a /boot/something.efi
- Don't really know what I am doing, but you can also go into "hybrid GPT" mode and "extended" settings where you can set something called "legacy bios boot flag"
- There is physical jumper on the motherboard called "ME_disabled" which is supposed required to update the bios, tried it on and off
- There is a physical jumper on the motherboard called "bios protect" tried it on and off
- There is BIOS settings such as : setting a bios password, but I don't see anything about secure boot, or other non-order boot options, the usb drive does show up as UEFI when live booting works... but never saw the hard drive as UEFI option yet

- Tried a bunch of different USB creation tools, but Rufus using dd mode seems to be the only one that boots live
```

I guess my next steps are to try and learn the entirety of how Grub works and try and troubleshoot that? Or is it obvious that no "boot flag" is surviving hardware reset is the problem?

**Comment by zlogic** [comment]
The issue is fixed in https://github.com/rancher/k3os/releases/tag/v0.20.4-k3s1r0
