### ISSUE TITLE
Question: how-to configure connman during imaging process

### ISSUE THREAD

**Issue by joharper54SEG** [rancher/k3os#238]
I have a need to modify the DHCP VendorClassID in order to pull an IP during the imaging process.  I have been building a custom ISO with some modifications to grub.cfg and net-online.  I think I need to run a connman command like "connmanctl config $ETH0 --VendorClassID=string" which will modify the main.cfg with the correct option.  Where would be the best place to put this in the image so that upon ISO boot this custom VendorClassID gets put in the DHCP packet?

I only need this option to be set during imaging time.  After the image is layed down it is configured to pull a config.yaml that will set a static IP based on the device's location going forward.  I use DHCP to determine the device location but it requires a custom VendorClass to pull an address.

**Comment by dweomer** [comment]
Please see https://github.com/rancher/k3os/issues/68#issuecomment-492089070 for some inspiration on how to do the `connman`+`write_files`+`run_cmd` dance in your config.yaml. Ideally, you should be able to do a `write_files` that emits a drop-in that connman will pick up but because we are talking about connman configuration here combined with conditional application of such, you will likely need the imperative glue.

**Comment by joharper54SEG** [comment]
Thanks Jacob.  I am a bit familiar with #68 as I am using that method to set the static IP after imaging is done.  The part I am struggling with is how to bake a config.yaml or connman config into the source before I issue make and build the ISOs.  Since I won't have any networking yet, I won't be able to pull in the config from my network source so the yaml that does the run_cmd needs to be done on 1st boot of the ISO before networking comes up so I can pull an IP and let the grub option "k3os.install.config_url" take it from there.

**Comment by dweomer** [comment]
@joharper54SEG I went back and visited #203 because your follow-up comment jogged my memory. I assume that you've already read https://github.com/rancher/k3os#remastering-iso and are looking for an easier, automated way of getting your config.yaml onto the ISO. There isn't a pre-canned way to do this but if you drop your `config.yaml` into [images/06-iso](https://github.com/rancher/k3os/tree/master/images/06-iso) and then modify the `Dockerfile` therein to `COPY` it to `/usr/src/iso/k3os/system/config.yaml` you should get the desired result.

**Comment by dweomer** [comment]
@joharper54SEG please see #240 for an example.

**Comment by joharper54SEG** [comment]
@dweomer Thanks for the help!  Modifying the dockerfile to drop the config in did the trick.
