### ISSUE TITLE
Configure private repo

### ISSUE THREAD

**Issue by mstoffel-sag** [rancher/k3os#396]
Hi k3os Team,

thanks for this great project!

I have a private repo that has a  cert configured that I have created to pull images from. On deployment in k3os I always get:

x509: certificate signed by unknown authority

I have the ca.crt file but I dont know where to put it. I saw https://rancher.com/docs/k3s/latest/en/installation/private-registry/
but how does that apply to k3os?

Thanks,

Marco

**Comment by dweomer** [comment]
@mstoffel-sag you should be able to put it wherever you like but I would recommend a persistent volume such as `/var/lib/rancher/k3s/registries/<registry domain>/ca.crt`.

Additionally, you will want to configure a `/var/lib/rancher/k3s/registries.yaml` referring to your registry and specifying the `ca_file` property mentioned [here](https://rancher.com/docs/k3s/latest/en/installation/private-registry/#configs) with your `ca.crt`. Make sure to let k3s know it is at a non-default location (because `/etc/rancher/k3s` is ephemeral), i.e.:
```shell
# config.yaml
k3os
  k3s_args:
    - "agent" # also on server(s) if they will run workloads based on images from the private registry
    - "--private-registry=/var/lib/rancher/k3s/registries.yaml"
    - ...
```

**Comment by mstoffel-sag** [comment]
Thanks!

I tried that, but somehow its not working. My config.yaml looks like:

ssh_authorized_keys:
- ssh-rsa XX

k3os:
  dns_nameservers:
  - 8.8.8.8
  k3s_args:
  - server
  - "--private-registry=/var/lib/rancher/k3s/registries.yaml"



time="2020-03-17T09:11:35Z" level=fatal msg="flag provided but not defined: -agent"
Incorrect Usage: flag provided but not defined: -agent

I had the agent setting configured like you suggested but removed it due to the error. Even the agent parameter is no longer set it still complains about and k3s is not starting.

**Comment by mstoffel-sag** [comment]
Even after removing all the k3s_args from config.yaml I still get the error. Is the config somehow cached?

**Comment by dweomer** [comment]
@mstoffel-sag k3os looks for config in a number of places and "merges" (overlay for the most part) them together which can look like caching. the order in which k3os merges config is:
- `/k3os/system/config.yaml`
- `/proc/cmdline` // kernel params
- `/var/lib/rancher/k3os/config.yaml`
- `/var/lib/rancher/k3os/config.d/*.yaml`
- `/run/config/userdata` // when configured with data source(s)

to see the current config as k3os sees it, you can run `sudo k3os config --dump`

**Comment by mstoffel-sag** [comment]
Did a new install. Its working now!
