### ISSUE TITLE
[Question] Automatic Updates

### ISSUE THREAD

**Issue by mstoffel-sag** [rancher/k3os#414]
Hi,

I'm running k3os version v0.9.1 and like to enable automatic updates. I read through the docs which are saying:

> Integration with rancher/system-upgrade-controller has been implemented as of v0.9.0. To enable a k3OS node to automatically upgrade from the latest GitHub release you will need to make sure it has the label plan.upgrade.cattle.io/k3os-latest with a value anything other than disabled.

Sorry this might be a dumb question but how can I enable that? In which file do I find that plan?

Thanks,

Marco

**Comment by dweomer** [comment]
> I'm running k3os version v0.9.1 and like to enable automatic updates. I read through the docs which are saying:
> 
> > Integration with rancher/system-upgrade-controller has been implemented as of v0.9.0. To enable a k3OS node to automatically upgrade from the latest GitHub release you will need to make sure it has the label plan.upgrade.cattle.io/k3os-latest with a value anything other than disabled.
> 
> Sorry this might be a dumb question but how can I enable that? In which file do I find that plan?

@mstoffel-sag not a dumb question. The default plan, `k3os-latest`, and system-upgrade-controller deployment is copied to `/var/lib/rancher/k3s/server/manifests` at boot time and sourced from there by k3s when it starts up. To make a node eligible for `k3os-latest` plan to be applied to it, label the node `plan.upgrade.cattle.io/k3os-latest`, e.g.:
```
# this will apply to all nodes. if your cluster is hetergeneous, adjust accordingly
kubectl label node --all plan.upgrade.cattle.io/k3os-latest=enabled
```

**Comment by mstoffel-sag** [comment]
Thanks! Did what you said. But nothing happens on reboot.

**Comment by dweomer** [comment]
> Thanks! Did what you said. But nothing happens on reboot.

No need to reboot after labeling a node.

The `k3os-latest` plan is setup to query https://github.com/rancher/k3os/releases/latest which currently redirects to [v0.9.1](https://github.com/rancher/k3os/releases/tag/v0.9.1)  (the latest, non-pre-release).

If you are running v0.9.1 then, unless you were actively watching pods on the node(s) (you would see traefik, metrics, local-path-provisioner, and coredns pods all get terminated and then go to pending), the only thing that I would expect to see change is the value of the label for `plan.upgrade.cattle.io/k3os-latest` on your node(s). This is because the upgrade process noticed that it had nothing to update and so no reboot happened and then when the upgrade was done being applied the controller modified the node's label to record the application of the plan (and at the same time marked the node as schedulable).

You should be able to see this on your node by running `kubectl get node -o json | jq -r '.items[].metadata.labels'` which will get you output that looks like:
```json
{
  "beta.kubernetes.io/arch": "amd64",
  "beta.kubernetes.io/instance-type": "k3s",
  "beta.kubernetes.io/os": "linux",
  "k3os.io/mode": "local",
  "k3os.io/version": "v0.9.1",
  "k3s.io/hostname": "k3os-31921",
  "k3s.io/internal-ip": "10.0.2.15",
  "kubernetes.io/arch": "amd64",
  "kubernetes.io/hostname": "k3os-31921",
  "kubernetes.io/os": "linux",
  "node-role.kubernetes.io/master": "true",
  "node.kubernetes.io/instance-type": "k3s",
  "plan.upgrade.cattle.io/k3os-latest": "249945707e471ac21ecb8fd0bb8225a3b3e07d1204b4d7dc1e72f9ed"
}
```

Notice that the value for `plan.upgrade.cattle.io/k3os-latest` is no longer `enabled`.

If you describe the `k3os-latest` plan you will see that value for the plan label matches the plan's `.status.latestHash`, e.g.:
```bash
$ kubectl get -o json -n k3os-system plan/k3os-latest | jq -r .status.latestHash
249945707e471ac21ecb8fd0bb8225a3b3e07d1204b4d7dc1e72f9ed
```

---

If you want to upgrade to a pre-release version of k3OS, say [v0.10.0-rc1](https://github.com/rancher/k3os/releases/tag/v0.10.0-rc1) that I tagged today, you can run `kubectl -n k3os-system patch plan k3os-latest -p '{"spec":{"version":"v0.10.0-rc1"}}' --type=merge`. It will take at few minutes to apply (I like to do a `watch kubectl get all -A` during an upgrade to see the drain happen). You may notice that on a slow connection that the `apply-k3os-latest-on-*` pod(s) appear to be stuck at `PodInitializing` but this is because the upgrade is downloading the rancher/k3os:v0.10.0-rc1 image which is over 400MB.

**Comment by mstoffel-sag** [comment]
Thank you very much for that detailed explanation! Will watch and report on the next release.....

**Comment by mstoffel-sag** [comment]
Hi,

hence there is a new release I tested what is happening. After booting the system would reboot automatically.  After that I queried:

k3os [~]$ kubectl get -o json -n k3os-system plan/k3os-latest | jq -r .status.latestHash
539c669e033d2412b0a998e19d789809e8cab1f1dc650802cd4548c3
k3os [~]$ kubectl get node -o json | jq -r '.items[].metadata.labels'
{
  "beta.kubernetes.io/arch": "amd64",
  "beta.kubernetes.io/instance-type": "k3s",
  "beta.kubernetes.io/os": "linux",
  "k3os.io/mode": "local",
  "k3os.io/version": "v0.10.0",
  "k3s.io/hostname": "k3os",
  "k3s.io/internal-ip": "192.168.186.11",
  "kubernetes.io/arch": "amd64",
  "kubernetes.io/hostname": "k3os",
  "kubernetes.io/os": "linux",
  "node-role.kubernetes.io/master": "true",
  "node.kubernetes.io/instance-type": "k3s",
  "plan.upgrade.cattle.io/k3os-latest": "249945707e471ac21ecb8fd0bb8225a3b3e07d1204b4d7dc1e72f9ed"


and after a while again:

k3os [~]$ kubectl get -o json -n k3os-system plan/k3os-latest | jq -r .status.latestHash
539c669e033d2412b0a998e19d789809e8cab1f1dc650802cd4548c3
k3os [~]$ kubectl get node -o json | jq -r '.items[].metadata.labels'
{
  "beta.kubernetes.io/arch": "amd64",
  "beta.kubernetes.io/instance-type": "k3s",
  "beta.kubernetes.io/os": "linux",
  "k3os.io/mode": "local",
  "k3os.io/version": "v0.10.0",
  "k3s.io/hostname": "k3os",
  "k3s.io/internal-ip": "192.168.186.11",
  "kubernetes.io/arch": "amd64",
  "kubernetes.io/hostname": "k3os",
  "kubernetes.io/os": "linux",
  "node-role.kubernetes.io/master": "true",
  "node.kubernetes.io/instance-type": "k3s",
  "plan.upgrade.cattle.io/k3os-latest": "539c669e033d2412b0a998e19d789809e8cab1f1dc650802cd4548c3"


Now the hash is the same as in the lable. Can you confirm that now the update is successfully finished?

Thanks Marco

**Comment by dweomer** [comment]
@mstoffel-sag the hash being the same as the label is indication that the upgrade was successful
