### ISSUE TITLE
Pods do not inherit k3OS' DNS server

### ISSUE THREAD

**Issue by giannoug** [rancher/k3os#680]
**Version (k3OS / kernel)**

`k3os version v0.20.4-k3s1r0`

`5.4.0-70-generic #78 SMP Fri Mar 26 17:09:23 UTC 2021`

**Architecture**

`x86_64`

**Describe the bug**

On a fresh install of k3OS (cloud config only contains SSH public keys), pods seem to not be using the DNS server of k3OS.

**To Reproduce**

Install latest k3OS and try to resolve a local LAN hostname (most home routers provide this functionality out of the box).

Running `kubectl run -it --rm --restart=Never busybox --image=busybox:1.28 -- nslookup router.lan` I expect `nslookup` to be able to resolve my custom hostname, since k3OS is using a DHCP-provided DNS server and is able to resolve it. This is what I'm getting instead:

```
Server:    10.43.0.10
Address 1: 10.43.0.10 kube-dns.kube-system.svc.cluster.local

nslookup: can't resolve 'router.lan'
```

Note that k3OS is able to resolve the hostname:
```
k3os-24066 [~]$ nslookup router.lan
Server:         192.168.1.1
Address:        192.168.1.1:53

Name:   router.lan
Address: 192.168.1.1

Non-authoritative answer:
```

**Expected behavior**

DNS resolving from inside the pod should work and return the correct IP, just as k3OS does.

**Actual behavior**

Resolving fails.

**Additional context**

Not relevant but k3OS is running as a VM.

This might help too:
```
kubectl run -i --restart=Never --rm test-${RANDOM} --image=ubuntu -- sh -c 'cat /etc/resolv.conf'
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.43.0.10
options ndots:5
pod "test-10461" deleted
```
```
kubectl run -i --restart=Never --rm test-${RANDOM} --image=ubuntu --overrides='{"kind":"Pod", "apiVersion":"v1", "spec": {"dnsPolicy":"Default"}}' -- sh -c 'cat /etc/resolv.conf'
nameserver 8.8.8.8
pod "test-5910" deleted
```

**Comment by moduspwnens** [comment]
I'm not involved with the k3os project but I did run into this issue when running on Oracle's Cloud.

On Oracle's Cloud, the IP address of the DNS server provided via DHCP is in the 169.254/16 range. This was causing k3s to presume it'd be better off using 8.8.8.8 instead. That's not an unreasonable assumption, but it did present an unexpected hurdle.

Ended up working around this by using the `--resolv-conf` arg to k3s and just passing in the default path (`/etc/resolv.conf`). That was enough for k3s to just use what's there instead of presuming it knows better.

I think I tracked the relevant line of code to the k3s project here:
https://github.com/k3s-io/k3s/blob/2705431d9645d128441c578309574cd262285ae6/pkg/agent/config/config.go#L277

And I'm not an expert in golang, but the documentation of that function seems to be here:
https://golang.org/pkg/net/#IP.IsGlobalUnicast

Hope it helps either you or someone who finds this later on.

**Comment by giannoug** [comment]
Interestingly enough, I gave this a try again on `v0.20.7-k3s1r0` and it seems to be working as expected. I can't say for sure that the newer version fixed the issue since I also changed hypervisors in the meantime.

The following works now:
```
kubectl run -it --rm --restart=Never busybox --image=busybox:1.28 -- nslookup server.lan
Server:    10.43.0.10
Address 1: 10.43.0.10 kube-dns.kube-system.svc.cluster.local

Name:      server.lan
Address 1: 192.168.1.165 server.lan
pod "busybox" deleted
```
