### ISSUE TITLE
install.sh: get_url never fails

### ISSUE THREAD

**Issue by acuteaura** [rancher/k3os#721]
Since c9144ab9da8cad85c52553469b7005c1adb31823, install.sh will swallow errors after attempts have run out, leading to misleading errors down the line (e.g. mount complaining about missing loop device)

**Comment by philomory** [comment]
As an example of the kind of error this can lead to, if you've got a custom ISO that sets the `k3os.install.config_url` kernel parameter in `grub.conf`, and that URL is inaccessible when booting from the ISO, the k3os install process will just proceed without a config.yaml file eventually, rather than aborting. This leads to an installation that _appears_ successful, but which is essentially unusable, because there's no password or SSH keys so you have no way to log in.
