### ISSUE TITLE
Open VM Tools are not properly working

### ISSUE THREAD

**Issue by JOduMonT** [rancher/k3os#735]
When I deploy k3os on Proxmox I see open-vm-tools and QEMU Guest Agent Starting
![image](https://user-images.githubusercontent.com/5204724/128676530-ff02d4fe-6afa-4f1b-9276-3d347930e391.png)

But at the end Proxmox is unable to manage the VM
![image](https://user-images.githubusercontent.com/5204724/128676616-63509451-5caa-454c-8859-386ee7e7f5b2.png)

It results than k3os have to be kill when I stop Proxmox and the backup from Proxmox fail for the VM.

**Comment by dweomer** [comment]
IIRC the services delivered by open-vm-tools package are specific to guests on vmware installations. Such is enabled by default but fails silently for anything other than a vmware guest. However, because we are talking proxmox what we should be concerned with is enabling and configuring the qemu guest agent which in almost all use-cases is not functional out of the box (regardless that qemu guest agent is only started for qemu guests after some `virt-what` introspection). Please see this issue thread for hinting on how to get that working: https://github.com/rancher/k3os/issues/291#issuecomment-560246793. Additionally, please note that this thread predates the switch to udev and so the `org.qemu.guest_agent.#` device(s) under the `/dev` hierarchy (I forget the sub-path) should show up automatically which may help make the setup of the `GA_PATH` envvar in the `/etc/conf.d/qemu-guest-agent` configuration file less error-prone.

**Comment by JOduMonT** [comment]
> [#291 (comment)](https://github.com/rancher/k3os/issues/291#issuecomment-560246793)
Thanks for your time and the explanation and not just simply tagging my issue as a duplicate and closing it :)
