### ISSUE TITLE
config init_cmd is not working

### ISSUE THREAD

**Issue by tfiduccia** [rancher/k3os#92]
Version - v0.2.1-rc2

Steps:
1.  Create a config.yaml with:
```
ssh_authorized_keys:
- github:<username>
init_cmd:
- "echo 'init command' && sleep 120"
k3os:
  password: asdf
```
2.  During boot process, press e to get into GNU Grub
3.  On linux cmdline add ```k3os.mode=install k3os.install.config_url=<raw path of config.yml>```

Results:  The init command never get run. The terminal never sleeps or print out the echo.

**Comment by dweomer** [comment]
There is currently no way to pass `init_cmd` via `config.yaml` because at the `initrd` phase the system is mid-pivot (prior to mounting persistent disk or source cdrom in the expected places) which means there is no standard place available for `ccapply` to pickup this configuration. #218 has fixed the parsing of quoted kernel parameters which means that `init_cmd` does work, but only as a kernel parameter.
